import type { CardDefinition } from '@/lib/gacha/common/types';

export const KENTA_CARDS: CardDefinition[] = [
  {
    cardId: 'card01_convenience',
    name: 'コンビニ夜勤バイト',
    title: '闇のレジ番',
    rarity: 'N',
    starRating: 1,
    mainSceneSteps: 2,
  },
  {
    cardId: 'card02_warehouse',
    name: '派遣倉庫作業員',
    title: '終わらない仕分け',
    rarity: 'N',
    starRating: 2,
    mainSceneSteps: 2,
  },
  {
    cardId: 'card03_youtuber',
    name: '底辺YouTuber',
    title: '再生数10の壁',
    rarity: 'R',
    starRating: 3,
    mainSceneSteps: 3,
  },
  {
    cardId: 'card04_civil_servant',
    name: '地方公務員',
    title: '窓口ルーティン',
    rarity: 'R',
    starRating: 4,
    mainSceneSteps: 3,
  },
  {
    cardId: 'card05_ramen',
    name: 'ラーメン屋店主',
    title: '魂の一杯',
    rarity: 'SR',
    starRating: 5,
    mainSceneSteps: 3,
  },
  {
    cardId: 'card06_boxer',
    name: 'プロボクサー',
    title: 'リングの覚悟',
    rarity: 'SR',
    starRating: 6,
    mainSceneSteps: 3,
  },
  {
    cardId: 'card07_surgeon',
    name: '天才外科医',
    title: '一刀入魂',
    rarity: 'SSR',
    starRating: 7,
    mainSceneSteps: 4,
  },
  {
    cardId: 'card08_business_owner',
    name: '実業家',
    title: '摩天楼の野望',
    rarity: 'SSR',
    starRating: 8,
    mainSceneSteps: 4,
  },
  {
    cardId: 'card09_mercenary',
    name: '異世界傭兵',
    title: '剣と契約',
    rarity: 'UR',
    starRating: 9,
    mainSceneSteps: 4,
  },
  {
    cardId: 'card10_rockstar',
    name: '伝説のロックスター',
    title: '轟音の祝祭',
    rarity: 'UR',
    starRating: 10,
    mainSceneSteps: 4,
  },
  {
    cardId: 'card11_demon_king',
    name: '魔王',
    title: '禍々しき覇王',
    rarity: 'LR',
    starRating: 11,
    mainSceneSteps: 5,
  },
  {
    cardId: 'card12_hero',
    name: '勇者',
    title: '光の継承者',
    rarity: 'LR',
    starRating: 12,
    mainSceneSteps: 5,
  },
];

export const KENTA_CARD_DESCRIPTIONS: Record<string, string> = {
  card01_convenience: '深夜のコンビニで幽霊客と常連に挟まれる庶民ルート。',
  card02_warehouse: '巨大倉庫で黙々と荷物をさばき、汗で未来を切り開くルート。',
  card03_youtuber: '投稿ボタンを押すたびに再生数を祈る、底辺配信者の奮闘。',
  card04_civil_servant: '役所カウンターの静寂で、慎重に「市民の声」と向き合う毎日。',
  card05_ramen: '魂のスープを仕込み、湯気の向こうに行列を夢見る屋台主。',
  card06_boxer: '血と汗と挑戦状。ゴングにすべてを賭けるリングサイド。',
  card07_surgeon: '命を預かる手が震えを知らない、閃光のスカルペル。',
  card08_business_owner: '摩天楼の頂から次の市場を睨む、連続起業家の野望。',
  card09_mercenary: '異世界で剣と契約を交わし、運命を金色に塗り替える傭兵。',
  card10_rockstar: '満員アリーナを轟音で掌握する、伝説級フロントマン。',
  card11_demon_king: '禍々しい玉座で世界を見下ろす、恐怖の支配者。',
  card12_hero: '聖剣と共に光を継ぎ、最後の希望として立ち上がる勇者。',
};
