import type { CardDefinition } from '@/lib/gacha/common/types';

export const YAHEI_CARDS: CardDefinition[] = [
  {
    cardId: 'card01_dinosaur',
    name: '恐竜時代転生',
    title: '原始時代のパニック',
    rarity: 'N',
    starRating: 1,
    mainSceneSteps: 2,
  },
  {
    cardId: 'card02_convenience',
    name: 'コンビニ店員転生',
    title: '現代日本のカルチャーショック',
    rarity: 'N',
    starRating: 2,
    mainSceneSteps: 2,
  },
  {
    cardId: 'card03_sns',
    name: 'SNS炎上転生',
    title: 'うっかり投稿で大炎上',
    rarity: 'R',
    starRating: 3,
    mainSceneSteps: 3,
  },
  {
    cardId: 'card04_rojyu',
    name: '江戸幕府老中転生',
    title: '同じ江戸時代なのに超出世',
    rarity: 'R',
    starRating: 4,
    mainSceneSteps: 3,
  },
  {
    cardId: 'card05_astronaut',
    name: '宇宙飛行士転生',
    title: 'NASAの宇宙飛行士',
    rarity: 'SR',
    starRating: 5,
    mainSceneSteps: 3,
  },
  {
    cardId: 'card06_noble',
    name: 'ヨーロッパ貴族転生',
    title: '19世紀フランス貴族のお屋敷生活',
    rarity: 'SR',
    starRating: 6,
    mainSceneSteps: 3,
  },
  {
    cardId: 'card07_sushi',
    name: '寿司職人転生',
    title: '魚の知識が現代で花開く',
    rarity: 'SSR',
    starRating: 7,
    mainSceneSteps: 4,
  },
  {
    cardId: 'card08_sumo',
    name: '大相撲横綱転生',
    title: '江戸っ子魂で横綱に',
    rarity: 'SSR',
    starRating: 8,
    mainSceneSteps: 4,
  },
  {
    cardId: 'card09_hollywood',
    name: 'ハリウッド俳優転生',
    title: 'アメリカでスター俳優',
    rarity: 'UR',
    starRating: 9,
    mainSceneSteps: 4,
  },
  {
    cardId: 'card10_shogun',
    name: '江戸城将軍転生',
    title: 'まさかの徳川将軍',
    rarity: 'UR',
    starRating: 10,
    mainSceneSteps: 4,
  },
  {
    cardId: 'card11_president',
    name: 'アメリカ大統領転生',
    title: '第○代アメリカ大統領',
    rarity: 'LR',
    starRating: 11,
    mainSceneSteps: 5,
  },
  {
    cardId: 'card12_timetravel',
    name: 'タイムトラベラー転生',
    title: '全時代を旅する時の番人',
    rarity: 'LR',
    starRating: 12,
    mainSceneSteps: 5,
  },
];

export const YAHEI_CARD_DESCRIPTIONS: Record<string, string> = {
  card01_dinosaur: '江戸っ子魂で白亜紀を駆け抜けるサバイバル開幕。',
  card02_convenience: '最新文化に翻弄されつつレジを守る深夜の店番修行。',
  card03_sns: 'てやんでぃ節が世界中に炎上拡散して大騒動。',
  card04_rojyu: 'まさかの重役入りで江戸城トップ層に殴り込み。',
  card05_astronaut: '天秤棒を宇宙服に持ち替えてNASAの船で大冒険。',
  card06_noble: 'パリの宮殿でマナー特訓、江戸言葉がサロンを席巻。',
  card07_sushi: '魚河岸仕込みの目利きがミシュラン級カウンターで炸裂。',
  card08_sumo: '土俵入りも江戸仕込み、情熱で横綱にまで上り詰める。',
  card09_hollywood: 'SNSバズから一気にレッドカーペットの主役に抜擢。',
  card10_shogun: '庶民目線の施策で江戸を救うカリスマ将軍伝説。',
  card11_president: '江戸っ子気質でホワイトハウスの政治をぶん回す。',
  card12_timetravel: '全時代を股にかけ魚籠片手に因果を見守る最終形態。',
};
