import type { CardDefinition } from '@/lib/gacha/common/types';

export const SHOICHI_CARDS: CardDefinition[] = [
  {
    cardId: 'card01_fish',
    name: '魚',
    title: '水槽の金魚',
    rarity: 'N',
    starRating: 1,
    mainSceneSteps: 2,
  },
  {
    cardId: 'card02_train',
    name: '満員電車の男',
    title: '永遠に降りられない電車',
    rarity: 'N',
    starRating: 2,
    mainSceneSteps: 2,
  },
  {
    cardId: 'card03_host',
    name: 'ホスト見習い',
    title: 'モテない夜の戦士',
    rarity: 'R',
    starRating: 3,
    mainSceneSteps: 3,
  },
  {
    cardId: 'card04_rehire',
    name: '再雇用おじさん',
    title: '定年後の嘱託社員',
    rarity: 'R',
    starRating: 4,
    mainSceneSteps: 3,
  },
  {
    cardId: 'card05_bear',
    name: '秋田のクマ',
    title: '人里に降りた熊',
    rarity: 'SR',
    starRating: 5,
    mainSceneSteps: 3,
  },
  {
    cardId: 'card06_ikemen',
    name: 'イケメン無双',
    title: 'マッチングアプリの覇者',
    rarity: 'SR',
    starRating: 6,
    mainSceneSteps: 3,
  },
  {
    cardId: 'card07_beach_bar',
    name: 'ビーチバー経営者',
    title: 'タイの自由人',
    rarity: 'SSR',
    starRating: 7,
    mainSceneSteps: 4,
  },
  {
    cardId: 'card08_revenge_boss',
    name: '逆転上司',
    title: '復讐を超えた部長',
    rarity: 'SSR',
    starRating: 8,
    mainSceneSteps: 4,
  },
  {
    cardId: 'card09_youth_love',
    name: '青春リベンジ',
    title: '22歳の大恋愛',
    rarity: 'UR',
    starRating: 9,
    mainSceneSteps: 4,
  },
  {
    cardId: 'card10_happy_family',
    name: '幸せ家庭',
    title: '4人家族の父',
    rarity: 'UR',
    starRating: 10,
    mainSceneSteps: 4,
  },
  {
    cardId: 'card11_pilot',
    name: '国際線パイロット',
    title: 'モテモテキャプテン',
    rarity: 'LR',
    starRating: 11,
    mainSceneSteps: 5,
  },
  {
    cardId: 'card12_investor',
    name: '巨額投資家',
    title: 'プライベートジェットの男',
    rarity: 'LR',
    starRating: 12,
    mainSceneSteps: 5,
  },
];

export const SHOICHI_CARD_DESCRIPTIONS: Record<string, string> = {
  card01_fish: '暗い水槽の中で静かに揺らめくだけの、息苦しい転生ルート。',
  card02_train: '永遠に止まらない満員電車で押しつぶされ続ける、終わりなき通勤地獄。',
  card03_host: 'ネオン街の片隅で声をかけても誰にも振り向かれない、切ない夜の修行。',
  card04_rehire: '定年後、元部下に敬語を使いながら小さなデスクで働き続ける現実。',
  card05_bear: '秋田の山奥で人里に降りれば迷惑者扱いされる、孤独なクマとしての人生。',
  card06_ikemen: 'マッチングアプリで連日マッチ通知が鳴り止まない、容姿チートな人生。',
  card07_beach_bar: 'タイのビーチで夕日を眺めながら、気ままにバーを回す脱サラ自由人。',
  card08_revenge_boss: 'かつて自分をいじめた上司を部下に従え、静かに立場を逆転させた部長ルート。',
  card09_youth_love: '二度目の青春で、憧れだったような大恋愛に全力で飛び込むやり直しルート。',
  card10_happy_family: '温かい食卓と子どもたちの笑い声に囲まれた、理想的な家庭持ち人生。',
  card11_pilot: '世界中の空を飛び回り、憧れの視線を一身に集める国際線キャプテン。',
  card12_investor: 'プライベートジェットで世界を飛び回る、桁違いの資産を持つ投資家。',
};
