import type { CardDefinition } from '@/lib/gacha/common/types';

export const TATUMI_CARDS: CardDefinition[] = [
  {
    cardId: 'card01_stone',
    name: '石ころ転生',
    title: '道端の石ころ',
    rarity: 'N',
    starRating: 1,
    mainSceneSteps: 2,
  },
  {
    cardId: 'card02_bug',
    name: '虫転生',
    title: '名もなき虫',
    rarity: 'N',
    starRating: 2,
    mainSceneSteps: 2,
  },
  {
    cardId: 'card03_flower',
    name: '野花転生',
    title: 'アスファルトの隙間の花',
    rarity: 'R',
    starRating: 3,
    mainSceneSteps: 3,
  },
  {
    cardId: 'card04_prison',
    name: '塀の中転生',
    title: '刑務所10年',
    rarity: 'R',
    starRating: 4,
    mainSceneSteps: 3,
  },
  {
    cardId: 'card05_father',
    name: '5人の父転生',
    title: '5人の子供を育てる父',
    rarity: 'SR',
    starRating: 5,
    mainSceneSteps: 3,
  },
  {
    cardId: 'card06_enma',
    name: '閻魔大王転生',
    title: '地獄の裁判官',
    rarity: 'SR',
    starRating: 6,
    mainSceneSteps: 3,
  },
  {
    cardId: 'card07_detective',
    name: '探偵所長転生',
    title: '裏社会知識を活かす探偵',
    rarity: 'SSR',
    starRating: 7,
    mainSceneSteps: 4,
  },
  {
    cardId: 'card08_buddha',
    name: '仏様転生',
    title: '慈悲の仏',
    rarity: 'SSR',
    starRating: 8,
    mainSceneSteps: 4,
  },
  {
    cardId: 'card09_martial',
    name: '武道家師範転生',
    title: '伝説の師',
    rarity: 'UR',
    starRating: 9,
    mainSceneSteps: 4,
  },
  {
    cardId: 'card10_actor',
    name: '映画俳優転生',
    title: '強面専門俳優',
    rarity: 'UR',
    starRating: 10,
    mainSceneSteps: 4,
  },
  {
    cardId: 'card11_dragon',
    name: '神龍転生',
    title: 'シェンロン',
    rarity: 'LR',
    starRating: 11,
    mainSceneSteps: 5,
  },
  {
    cardId: 'card12_enma_true',
    name: '閻魔大王（真）転生',
    title: '冥界統治者',
    rarity: 'LR',
    starRating: 12,
    mainSceneSteps: 5,
  },
];

export const TATUMI_CARD_DESCRIPTIONS: Record<string, string> = {
  card01_stone: '踏まれても砕けず、ただ静かに季節を見送る石ころ再起ルート。',
  card02_bug: '闇に怯えながらもひたすら生き抜く、名もなき虫の執着。',
  card03_flower: 'アスファルトを割って伸びる一輪の野花、無骨な優しさの芽吹き。',
  card04_prison: '塀の内側で己と向き合い続ける、10年の贖罪ロード。',
  card05_father: '5人の子どもを抱えて笑う、寡黙な父ちゃん第二章。',
  card06_enma: '地獄の裁判官として筋を通す、炎の玉座リターン。',
  card07_detective: '裏社会の勘をフル活用し、影の依頼を請け負う探偵所長。',
  card08_buddha: '慈悲と覚悟が極まった先、蓮の上で人を救う仏の微笑。',
  card09_martial: '道場の床を鳴らす一喝、拳で教え導く伝説師範。',
  card10_actor: 'スーツの裾を翻しスクリーンを支配する、強面専属俳優ルート。',
  card11_dragon: '涙が昇華して龍と化す、天空を旋回する神龍の覚醒。',
  card12_enma_true: '冥界を統治する究極の閻魔、全ての因果を見通す最終章。',
};
